import "./globals.css";
import "../components/Modal/modal.css";
import ToastProviders from "../components/Toast/ToastProviders";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastProviders>{children}</ToastProviders>
      </body>
    </html>
  );
}
