services:
  backend:
    build: ./backend
    ports:
      - "8088:8000"
    volumes:
      - ./backend:/app
      - ./inventario.xlsx:/app/inventario.xlsx:ro
      - ./planilha_campus_aracruz_05032025.xlsx:/app/planilha_campus_aracruz_05032025.xlsx:ro
      - backend-modules:/app/node_modules
      - backend-dev-data:/app/.dev-data
    environment:
      DATABASE_URL: "file:./.dev-data/dev.db"
      NODE_ENV: "development"
      XLSX_PATH: "/app/planilha_campus_aracruz_05032025.xlsx"
      LDAP_URL: "ldap://172.16.112.2:389"
      LDAP_BASE_DN: "OU=Usuarios,OU=Campus Aracruz,DC=cefetes,DC=br"
      LDAP_DOMAIN: "cefetes.br"
      LDAP_BIND_USER: "ldap.ar"
      LDAP_BIND_PASS: "Ld@p.@r"
      JWT_SECRET: "dev-secret-123-mude-em-producao"
    command: ["pnpm", "dev"]

  frontend:
    build: ./frontend
    ports:
      - "3033:3000"
    volumes:
      - ./frontend:/app
      - frontend-modules:/app/node_modules
      - frontend-cache:/app/.next
    environment:
      NEXT_PUBLIC_API_URL: "/api"
    command: ["pnpm", "dev"]
    depends_on:
      - backend

volumes:
  backend-modules:
  frontend-modules:
  frontend-cache:
  backend-dev-data:
